# brew tap-new uses this file to generate an actionlint workflow for the new tap
name: Actionlint

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -xeuo pipefail {0}

concurrency:
  group: "actionlint-${{ github.ref }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions: {}

jobs:
  workflow_syntax:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: ghcr.io/homebrew/brew:main # zizmor: ignore[unpinned-images]
    steps:
      - name: Set up Homebrew
        id: setup-homebrew
        uses: Homebrew/actions/setup-homebrew@848c272c7bfe984a197bd4d16383f4c106ec61e6 # 2026.09.21.1
        with:
          core: false
          cask: false

      - name: Install tools
        run: brew install actionlint shellcheck zizmor

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - run: zizmor .
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: actionlint